config/routes.rb
Rails.application.routes.draw do
  
  get 'files/new'
  devise_for :users, only: [:sessions], controllers: {
    sessions: 'users/sessions'
  }

  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'painel', to: 'static_pages#painel'
  get 'files/new'

  resources :bios, only: [:show, :update, :edit]
  resources :home_videos, only: [:show, :update, :edit]
  resources :publics
  resources :comments
  resources :teachers
  resources :contacts, only: [:show, :update, :edit] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord

  #validates
  validates :resume, presence: true, length: { maximum: 600 }

  validates :bio, length: { maximum: 2000 }, allow_blank: true

  validates :image, presence: true, allow_blank: true
  
  # Associations
  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  #validates
  validates :comment, presence: true, length: { maximum: 200 }

  validates :name, presence: true, length: { maximum: 24 }

  validates :image, presence: true, allow_blank: true
  
  # Associations
  has_one_attached :image
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home_video.rb
class HomeVideo < ApplicationRecord
  #validates
  validates :link, presence: true, length: { maximum: 300 }

  validates :title, presence: true, length: { maximum: 34 }

end

app/models/public.rb
class Public < ApplicationRecord
  #validates
  validates :resume, presence: true, length: { maximum: 94 }

  validates :title, presence: true, length: { maximum: 12 }

  validates :image, presence: true, allow_blank: true
  
  # Associations
  has_one_attached :image
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  #validates
  validates :name, presence: true, length: { maximum: 30 }

  validates :job, presence: true, length: { maximum: 30 }
  
  validates :image, presence: true, allow_blank: true

  # Associations
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bio
  
  layout "painel"

  def show
  end
  
  def edit
  end

  def update
    if @bio.update(bio_params)
      redirect_to @bio
    else 
      render 'edit'
    end
  end

  private
    
    def set_bio
      @bio = Bio.find(params[:id])
    end

    def bio_params
      params.require(:bio).permit(:resume, :bio, :image)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
  layout "painel"

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment
    else
      render 'new'
    end

  end

  
  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else 
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to comments_path
  end

  private
    
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:name, :comment, :image)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact
  
  layout "painel"

  def show
  end
  
  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact
    else 
      render 'edit'
    end
  end

  private
    
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:rua, 
                                      :numero, 
                                      :cep,
                                      :cidade,
                                      :uf,
                                      :phone_cell,
                                      :phone_fixed,
                                      :whatsapp,
                                      :att_week,
                                      :att_weekend,
                                      :email,
                                      :facebook,
                                      :instagram
                                      )
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_public, only: [:show, :edit, :update, :destroy]
  
  layout "painel"

  def index
    @publics = Public.all
  end

  def new
    @public = Public.new
  end

  def show
  end

  def create
    @public = Public.new(public_params)

    if @public.save
      redirect_to @public
    else
      render 'new'
    end

  end

  
  def edit
  end

  def update
    if @public.update(public_params)
      redirect_to @public
    else 
      render 'edit'
    end
  end

  def destroy
    @public.destroy
    redirect_to publics_path
  end

  private
    
    def set_public
      @public = Public.find(params[:id])
    end

    def public_params
      params.require(:public).permit(:resume, :title, :image)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  
  layout "painel"

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def show
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher
    else
      render 'new'
    end

  end

  
  def edit
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to @teacher
    else 
      render 'edit'
    end
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_path
  end

  private
    
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:name, :job, :facebook, :instagram, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/home_videos_helper.rb
module HomeVideosHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/bios/_form.html.erb
<%= form_for(@bio) do |f|%>

  <%= render 'devise/shared/error_messages', resource: f.object %>

  <div class="form-group field">
    <%= f.label :resume %><br />
    <%= f.text_area :resume, maxlength: 600, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, maxlength: 2000, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-secondary btn-block" %>
  </div>

<% end %>

app/views/bios/edit.html.erb
<h1>Atualizar Biografia</h1>

<%= render 'form' %>

app/views/bios/show.html.erb
<h1>Biografia</h1>

<div class="d-flex flex-row-reverse">
  <%= link_to "Editar", edit_bio_path(@bio), class: "btn btn-secondary"%>
</div>

<p>
  <strong>Resume</strong><br />
  <%= @bio.resume %>
</p>

<p>
  <strong>Biografia<strong><br />
  <%= @bio.bio %>
</p>

<p>
  <strong>Imagem<strong><br />
  <% if @bio.image.attached? %>
    <%= image_tag @bio.image.variant(resize: "500x500") %>
  <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f|%>

  <%= render 'devise/shared/error_messages', resource: f.object %>

  <div class="form-group field">
    <%= f.label :name %><br />
    <%= f.text_field :name, maxlength: 24, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, maxlength: 200, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-secondary btn-block" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Atualizar Comentário</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="d-flex flex-row-reverse">
  <%= link_to "Novo", new_comment_path, class: "btn btn-danger"%>
</div>
<h1>Comentários</h1>

<div clas="d-flex flex-column">

<% @comments.each do |comment| %>

  <div class="d-flex flex-row-reverse">
    <%= link_to 'Deletar', comment, method: :delete, data: { confirm: "Deseja deletar este commentário?" }, class: "btn btn-secondary"%>
    <%= link_to "Editar", edit_comment_path(comment), class: "btn btn-secondary"%>
  </div>

  <p>
    <strong>Nome</strong><br />
    <%= comment.name %>
  </p>

  <p>
    <strong>Comentário</strong><br />
    <%= comment.comment %>
  </p>

  <p>
    <strong>Imagem</strong><br />
    <% if comment.image.attached?%>
      <%= image_tag comment.image.variant(resize: "200x200") %>
    <% end %>
  </p>

  <hr />

<% end %>

</div>

app/views/comments/new.html.erb
<h1>Novo Comentário</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<h1><%= @comment.name %></h1>

<div class="d-flex flex-row-reverse">
  <%= link_to 'Deletar', @comment, method: :delete, data: { confirm: "Deseja deletar este commentário?" }, class: "btn btn-secondary"%>
  <%= link_to "Editar", edit_comment_path(@comment), class: "btn btn-secondary"%>
  <%= link_to "Novo", new_comment_path, class: "btn btn-danger"%>
</div>

<p>
  <strong>Comentário</strong><br />
  <%= @comment.comment %>
</p>

<p>
  <strong>Imagem<strong><br />
  <% if @comment.image.attached?%>
    <%= image_tag @comment.image.variant(resize: "200x200") %>
  <% end %>
</p>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f|%>

  <%= render 'devise/shared/error_messages', resource: f.object %>

  <div class="form-group field">
    <%= f.label :rua %><br />
    <%= f.text_field :rua, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :numero %><br />
    <%= f.text_field :numero, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :cidade %><br />
    <%= f.text_field :cidade, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :uf %><br />
    <%= f.text_field :uf, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :cep %><br />
    <%= f.text_field :cep, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :email %><br />
    <%= f.email_field :email, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <label>Telefone Celular</label><br />
    <%= f.text_field :phone_cell, maxlength: 14, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <label>Telefone Fixo</label><br />
    <%= f.text_field :phone_fixed, maxlength: 14, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <label>WhatsApp</label><br />
    <%= f.text_field :whatsapp, maxlength: 14, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <label>Facebook Link</label><br />
    <%= f.text_field :facebook, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <label>Instagram Link</label><br />
    <%= f.text_field :instagram, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-secondary btn-block" %>
  </div>

<% end %>

app/views/contacts/edit.html.erb
<h1>Atualizar Contatos</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1>Contato</h1>

<div class="d-flex flex-row-reverse">
  <%= link_to "Editar", edit_contact_path(@contact), class: "btn btn-secondary"%>
</div>

<p>
  <strong>Rua</strong><br />
  <%= @contact.rua %>
</p>

<p>
  <strong>Número</strong><br />
  <%= @contact.numero %>
</p>

<p>
  <strong>CEP</strong><br />
  <%= @contact.cep%>
</p>

<p>
  <strong>Cidade</strong><br />
  <%= @contact.cidade %>
</p>

<p>
  <strong>UF</strong><br />
  <%= @contact.uf %>
</p>

<p>
  <strong>Email</strong><br />
  <%= @contact.email %>
</p>

<p>
  <strong>Celular</strong><br />
  <%= @contact.phone_cell %>
</p>

<p>
  <strong>Telefone Fixo</strong><br />
  <%= @contact.phone_fixed %>
</p>

<p>
  <strong>WhatsApp</strong><br />
  <%= @contact.whatsapp %>
</p>

<p>
  <strong>Facebook Link</strong><br />
  <%= @contact.facebook %>
</p>

<p>
  <strong>Instagram Link</strong><br />
  <%= @contact.instagram %>
</p>

<p>
  <strong>Horário de atendimento na Semana</strong><br />
  <%= @contact.att_week %>
</p>

<p>
  <strong>Horário de atendimento no Sabado </strong><br />
  <%= @contact.att_weekend %>
</p>

app/views/publics/_form.html.erb
<%= form_for(@public) do |f|%>

  <%= render 'devise/shared/error_messages', resource: f.object %>

  <div class="form-group field">
    <%= f.label :title %><br />
    <%= f.text_field :title, maxlength: 12, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :resume %><br />
    <%= f.text_area :resume, maxlength: 94, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-secondary btn-block" %>
  </div>

<% end %>

app/views/publics/edit.html.erb
<h1>Atualizar</h1>

<%= render 'form' %>

app/views/publics/index.html.erb
<div class="d-flex flex-row-reverse">
  <%= link_to "Novo", new_public_path, class: "btn btn-danger"%>
</div>
<h1>Publico</h1>

<div clas="d-flex flex-column">

<% @publics.each do |publico| %>

  <div class="d-flex flex-row-reverse">
    <%= link_to 'Deletar', @public, method: :delete, data: { confirm: "Deseja deletar este publico?" }, class: "btn btn-secondary" %>
    <%= link_to "Editar", edit_public_path(publico), class: "btn btn-secondary" %>
    <%= link_to "Vizualizar", public_path(publico), class: "btn btn-secondary" %>
  </div>

  <p>
    <strong>Título</strong><br />
    <%= publico.title %>
  </p>

  <p>
    <strong>Resume</strong><br />
    <%= publico.resume %>
  </p>

  <p>
    <strong>Imagem</strong><br />
    <%= image_tag publico.image.variant(resize: "200x200") %>
  </p>

  <hr />

<% end %>

</div>

app/views/publics/new.html.erb
<h1>Novo Publico</h1>

<%= render 'form' %>

app/views/publics/show.html.erb
<h1><%= @public.title%></h1>

<div class="d-flex flex-row-reverse">
  <%= link_to 'Deletar', @public, method: :delete, data: { confirm: "Deseja deletar este publico?" }, class: "btn btn-secondary" %>
  <%= link_to "Editar", edit_public_path(@public), class: "btn btn-secondary"%>
  <%= link_to "Novo", new_public_path, class: "btn btn-danger"%>
</div>

<p>
  <strong>Resume</strong><br />
  <%= @public.resume %>
</p>

<p>
  <strong>Imagem<strong><br />
  <%= image_tag @public.image.variant(resize: "200x200") %>
</p>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f|%>

  <%= render 'devise/shared/error_messages', resource: f.object %>

  <div class="form-group field">
    <%= f.label :name %><br />
    <%= f.text_field :name, maxlength: 30, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :job %><br />
    <%= f.text_field :job, maxlength: 30, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.label :instagram %><br />
    <%= f.text_field :instagram, maxlength: 300, class: "form-control"  %>
  </div>

  <div class="form-group field">
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-secondary btn-block" %>
  </div>

<% end %>

app/views/teachers/edit.html.erb
<h1>Atualizar Professor</h1>

<%= render 'form' %>

app/views/teachers/index.html.erb
<div class="d-flex flex-row-reverse">
  <%= link_to "Novo", new_teacher_path, class: "btn btn-danger"%>
</div>
<h1>Professores</h1>

<div clas="d-flex flex-column">

<% @teachers.each do |teacher| %>

  <div class="d-flex flex-row-reverse">
    <%= link_to 'Deletar', teacher, method: :delete, data: { confirm: "Deseja deletar este professor?" }, class: "btn btn-secondary"%>
    <%= link_to "Editar", edit_teacher_path(teacher), class: "btn btn-secondary"%>
  </div>

  <p>
    <strong>Nome</strong><br />
    <%= teacher.name %>
  </p>

  <p>
    <strong>Disciplina</strong><br />
    <%= teacher.job %>
  </p>

  <p>
    <strong>Facebook Link</strong><br />
    <%= teacher.facebook %>
  </p>
  
  <p>
    <strong>Instagram Link</strong><br />
    <%= teacher.instagram %>
  </p>

  <p>
    <strong>Imagem</strong><br />
    <% if teacher.image.attached?%>
      <%= image_tag teacher.image.variant(resize: "200x200") %>
    <% end %>
  </p>

  <hr />

<% end %>

</div>

app/views/teachers/new.html.erb
<h1>Novo Professor</h1>

<%= render 'form' %>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %></h1>

<div class="d-flex flex-row-reverse">
  <%= link_to 'Deletar', @teacher, method: :delete, data: { confirm: "Deseja deletar este professor?" }, class: "btn btn-secondary"%>
  <%= link_to "Editar", edit_teacher_path(@teacher), class: "btn btn-secondary"%>
  <%= link_to "Novo", new_teacher_path, class: "btn btn-danger"%>
</div>

<p>
  <strong>Job</strong><br />
  <%= @teacher.job %>
</p>

<p>
  <strong>Facebook Link</strong><br />
  <%= @teacher.facebook %>
</p>

<p>
  <strong>Instagram Link</strong><br />
  <%= @teacher.instagram %>
</p>


<p>
  <strong>Imagem<strong><br />
  <% if @teacher.image.attached?%>
    <%= image_tag @teacher.image.variant(resize: "200x200") %>
  <% end %>
</p>