config/routes.rb
Rails.application.routes.draw do
  
  get 'files/new'
  devise_for :users, only: [:sessions], controllers: {
    sessions: 'users/sessions'
  }

  root 'static_pages#home'
  get 'home', to: 'static_pages#home'
  get 'painel', to: 'static_pages#painel'
  get 'files/new'

  resources :bios, only: [:show, :update, :edit]
  resources :home_videos, only: [:show, :update, :edit]
  resources :publics
  resources :comments
  resources :teachers
  resources :contacts, only: [:show, :update, :edit] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord

  #validates
  validates :resume, presence: true, length: { maximum: 600 }

  validates :bio, length: { maximum: 2000 }, allow_blank: true

  validates :image, presence: true, allow_blank: true
  
  # Associations
  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  #validates
  validates :comment, presence: true, length: { maximum: 200 }

  validates :name, presence: true, length: { maximum: 24 }

  validates :image, presence: true, allow_blank: true
  
  # Associations
  has_one_attached :image
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home_video.rb
class HomeVideo < ApplicationRecord
  #validates
  validates :link, presence: true, length: { maximum: 300 }

  validates :title, presence: true, length: { maximum: 34 }

end

app/models/public.rb
class Public < ApplicationRecord
  #validates
  validates :resume, presence: true, length: { maximum: 94 }

  validates :title, presence: true, length: { maximum: 12 }

  validates :image, presence: true, allow_blank: true
  
  # Associations
  has_one_attached :image
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  #validates
  validates :name, presence: true, length: { maximum: 30 }

  validates :job, presence: true, length: { maximum: 30 }
  
  validates :image, presence: true, allow_blank: true

  # Associations
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bio
  
  layout "painel"

  def show
  end
  
  def edit
  end

  def update
    if @bio.update(bio_params)
      redirect_to @bio
    else 
      render 'edit'
    end
  end

  private
    
    def set_bio
      @bio = Bio.find(params[:id])
    end

    def bio_params
      params.require(:bio).permit(:resume, :bio, :image)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
  layout "painel"

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def show
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment
    else
      render 'new'
    end

  end

  
  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else 
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to comments_path
  end

  private
    
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:name, :comment, :image)
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_public, only: [:show, :edit, :update, :destroy]
  
  layout "painel"

  def index
    @publics = Public.all
  end

  def new
    @public = Public.new
  end

  def show
  end

  def create
    @public = Public.new(public_params)

    if @public.save
      redirect_to @public
    else
      render 'new'
    end

  end

  
  def edit
  end

  def update
    if @public.update(public_params)
      redirect_to @public
    else 
      render 'edit'
    end
  end

  def destroy
    @public.destroy
    redirect_to publics_path
  end

  private
    
    def set_public
      @public = Public.find(params[:id])
    end

    def public_params
      params.require(:public).permit(:resume, :title, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/home_videos_helper.rb
module HomeVideosHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-danger" id="header">
  <div class="container">
    <%= image_tag 'logo.png', class: "navbar-brand d-block logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <%= link_to "Site", root_path, class: "nav-link"%>
        </li>
        
        <li class="nav-item active">
          <%= link_to "Painel", painel_path, class: "nav-link"%>
        </li>

        <li class="nav-item active dropdown">
          
          <a class="nav-link" 
              href="#" 
              id="homeDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true" 
              aria-expanded="false"
            >
            <%= icon('fas', 'caret-down') %>
            Home Page
          </a>

          <div class="dropdown-menu" aria-labelledby="homeDropdown">

            <% if !Bio.first.nil? %>
              <%= link_to "Biografia", bio_path(Bio.first), class: "dropdown-item"%>
            <% end %>
          
            <%= link_to "Temos turmas para", publics_path, class: "dropdown-item"%>
            
            <% if !HomeVideo.first.nil? %>
              <%= link_to "Home Video", home_video_path(HomeVideo.first), class: "dropdown-item"%>
            <% end %>
            
            <%= link_to "Comentários", comments_path, class: "dropdown-item"%>
            
            <%= link_to "Professores", teachers_path, class: "dropdown-item"%>

          </div>

        </li>
        
        <li class="nav-item active">
          <%= link_to "Contato", contact_path(Contact.first), class: "nav-link"%>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item active dropdown">
            <a class="nav-link" 
               href="#" 
               id="userDropdown"
               role="button"
               data-toggle="dropdown"
               aria-haspopup="true" 
               aria-expanded="false"
              >
              <%= icon('fas', 'user') %>
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="userDropdown">
              <%= link_to "Configurações", painel_path,  class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="navbar-nav mr-auto">
        <li class="nav-item active">
          <button class="btn btn-danger btn-block header-btn"> Matrícule-se </button>
        </li>
      </div>
    </div>
    </div>
</nav>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_carousel.html.erb
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag '10.jpg', class: "d-block w-100 carousel-img" %>
      <div class="carousel-caption">
        <h2 class="animated h2-animated fadeInDown">Elite Música</h2>
        <div class="animated p-animated fadeInUp">A Escola da Família para toda Família</div>
        <button class="btn btn-danger header-btn animated p-animated fadeInUp"> Matrícule-se </button>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag '15.jpg', class: "d-block w-100 carousel-img" %>
      <div class="carousel-caption">
        <h2 class="animated h2-animated fadeInLeftBig">Viva melhor com a Música</h2>
        <p class="animated p-animated fadeInRightBig">Temos turmas para todas idades</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag '14.jpg', class: "d-block w-100 carousel-img" %>
      <div class="carousel-caption">
        <h2 class="animated h2-animated flipInY">Qual som representa sua vida?</h2>
        <p class="animated p-animated flipInY">Estamos empenhados a descobrir junto como você</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="d-flex justify-content-around">
				<%= link_to image_tag('logo.png'), root_path, class: "navbar-brand" %>
        <p class="text-white copy-right">Elite Música © 2019. All rights reserved Terms of Use and Privacy Policy</p>
        <p class="text-white copy-right">Developed by Avitry Systems</p>
    </div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-danger" id="header">
  <div class="container">
    <%= image_tag 'logo.png', class: "navbar-brand d-block logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#about-us-link">A Escola</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#aulas-link">Cursos</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#turmas-link">Turmas</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#eventos-link">Eventos</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#contato-link">Contatos</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#localizacao-link">Localização</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active dropdown">
            <a class="nav-link" 
               href="#" 
               id="userDropdown"
               role="button"
               data-toggle="dropdown"
               aria-haspopup="true" 
               aria-expanded="false"
              >
              <%= icon('fas', 'user') %>
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="userDropdown">
              <%= link_to "Configurações", painel_path,  class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="navbar-nav mr-auto">
        <li class="nav-item active">
          <button class="btn btn-danger btn-block header-btn"> Matrícule-se </button>
        </li>
      </div>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elitemusica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/painel.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elitemusica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  </head>

  <body>

    <%= render 'layouts/admin_header' unless controller.controller_name == "sessions"%>
    <main class="container">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' unless controller.controller_name == "sessions" %>
  </body>
</html>